# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: da8ccb969e28ea48550c8685196d4c383bf8f4727d3d9e0dec6e7c4aa01f5041ef0b929fd0184827cb18efacc01b15207e431e169af3a5e29bcd5789e3cbea08

test:
  secret_key_base: 05ccc6ea3070373e8cce784e0272d71d0abe0601143155f57b567d9009c57f17dc4f0027c49bb1744374e4452a5f87c8bdf42c26e95680d0769bb6c7b0ed2659

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
